version: "3.7"
services:
  maria:
    environment:
      - MYSQL_PASSWORD=zbakhKStr543mT_OB/r}actiTSNHOT
  tinventory:
    build: .
    environment:
      - TINVENTORY_SECRET_KEY=tirnotaeronuadtirnDTNTORSOEDR78745289756Nrtiansetirnae
      - TINVENTORY_DEBUG_MODE=True
      - TINVENTORY_DB_PASSWORD=zbakhKStr543mT_OB/r}actiTSNHOT
      - TINVENTORY_SUPERUSER=admin
      - TINVENTORY_SUPERUSER_MAIL=admin@admin.com
      - TINVENTORY_SUPERUSER_PASSWORD=adminadmin
