# Generated by Django 2.1.5 on 2019-03-16 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_preset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
    ]
