# Generated by Django 2.1.5 on 2019-03-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20190316_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='image',
            field=models.FileField(blank=True, upload_to='images/presets/'),
        ),
    ]
