# Generated by Django 2.1.5 on 2019-03-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_preset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/presets/', verbose_name='Bild'),
        ),
    ]
