# Generated by Django 2.1.5 on 2019-03-24 17:19

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_auto_20190319_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('last_time_seen_at', models.DateTimeField(auto_now=True, verbose_name='Letztes Mal gesehen am')),
                ('category',
                 models.ForeignKey(default=api.models.default_category, on_delete=django.db.models.deletion.SET_DEFAULT,
                                   related_name='items', to='api.Category', verbose_name='Kategorie')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='items', to='api.Location', verbose_name='Ort')),
            ],
        ),
        migrations.AlterField(
            model_name='preset',
            name='category',
            field=models.ForeignKey(default=api.models.default_category,
                                    on_delete=django.db.models.deletion.SET_DEFAULT, related_name='presets',
                                    to='api.Category', verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='item',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='items', to='api.Preset', verbose_name='Preset'),
        ),
    ]
