# Generated by Django 2.1.5 on 2019-03-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_auto_20190324_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Objekt', 'verbose_name_plural': 'Objekte'},
        ),
        migrations.AlterField(
            model_name='location',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Schranknummer'),
        ),
    ]
