# Generated by Django 2.2.5 on 2019-09-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_auto_20190324_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Barcode'),
        ),
    ]
