# Generated by Django 2.2.5 on 2019-09-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_auto_20190916_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_within_school', models.BooleanField(default=False, verbose_name='Schulintern?')),
                ('is_technician', models.BooleanField(default=False, verbose_name='Aktiver Techniker?')),
            ],
        ),
    ]
