# Generated by Django 2.2.5 on 2019-09-17 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_check_checkoutprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='checks',
                                    to='api.Item', verbose_name='Objekt'),
            preserve_default=False,
        ),
    ]
