# Generated by Django 2.2.5 on 2019-09-18 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0014_check_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-In-Zeitpunkt'),
        ),
        migrations.AlterField(
            model_name='check',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='check_ins', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Check-In durchgeführt von'),
        ),
    ]
