# Generated by Django 2.2.5 on 2019-09-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0016_checkoutprocess_is_check_out_in_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutprocess',
            name='check_in_until',
            field=models.DateField(blank=True, null=True, verbose_name='Check-In bis'),
        ),
    ]
