# Generated by Django 2.2.5 on 2019-09-28 15:07

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Schranknummer')),
            ],
            options={
                'verbose_name': 'Ort',
                'verbose_name_plural': 'Orte',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_within_school', models.BooleanField(default=False, verbose_name='Schulintern?')),
                ('is_technician', models.BooleanField(default=False, verbose_name='Aktiver Techniker?')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personen',
            },
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Hersteller')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('image', models.ImageField(blank=True, upload_to='images/presets/', verbose_name='Bild')),
                ('category',
                 models.ForeignKey(default=api.models.default_category, on_delete=django.db.models.deletion.SET_DEFAULT,
                                   related_name='presets', to='api.Category', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Preset',
                'verbose_name_plural': 'Presets',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('barcode', models.CharField(blank=True, help_text='Frei lassen, um Barcode automatisch zu generieren',
                                             max_length=15, null=True, unique=True, verbose_name='Barcode')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('last_time_seen_at', models.DateTimeField(auto_now=True, verbose_name='Letztes Mal gesehen am')),
                ('category',
                 models.ForeignKey(default=api.models.default_category, on_delete=django.db.models.deletion.SET_DEFAULT,
                                   related_name='items', to='api.Category', verbose_name='Kategorie')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='items', to='api.Location', verbose_name='Ort')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='items', to='api.Preset', verbose_name='Preset')),
            ],
            options={
                'verbose_name': 'Objekt',
                'verbose_name_plural': 'Objekte',
            },
        ),
        migrations.CreateModel(
            name='CheckOutProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField(auto_now_add=True, verbose_name='Check-Out-Zeitpunkt')),
                ('is_check_out_in_process', models.BooleanField(default=True, verbose_name='Check-Out im Prozess?')),
                ('check_in_until', models.DateField(blank=True, null=True, verbose_name='Check-In bis')),
                ('borrowing_person',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_outs',
                                   to='api.Person', verbose_name='Ausleihende Person')),
                ('lending_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_outs',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Verleihender Nutzer')),
            ],
            options={
                'verbose_name': 'Check-Out-Vorgang',
                'verbose_name_plural': 'Check-Out-Vorgänge',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in', models.BooleanField(default=False, verbose_name='Check-In durchgeführt?')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Check-In-Zeitpunkt')),
                ('check_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks',
                                                to='api.CheckOutProcess', verbose_name='Check-Out-Vorgang')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='check_ins', to=settings.AUTH_USER_MODEL,
                                                    verbose_name='Check-In durchgeführt von')),
                ('item',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='api.Item',
                                   verbose_name='Objekt')),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
            },
        ),
    ]
