# Generated by Django 2.2.5 on 2019-09-17 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Personen'},
        ),
    ]
