# Generated by Django 2.2.5 on 2019-09-17 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_auto_20190917_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOutProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField(auto_now_add=True, verbose_name='Check-Out-Zeitpunkt')),
                ('check_in_until', models.DateTimeField(blank=True, null=True, verbose_name='Check-In bis')),
                ('borrowing_person',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_outs',
                                   to='api.Person', verbose_name='Ausleihende Person')),
                ('lending_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_outs',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Verleihender Nutzer')),
            ],
            options={
                'verbose_name': 'Check-Out-Vorgang',
                'verbose_name_plural': 'Check-Out-Vorgänge',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in', models.BooleanField(default=False, verbose_name='Check-In durchgeführt?')),
                ('checked_in_at', models.DateTimeField(verbose_name='Check-In-Zeitpunkt')),
                ('check_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks',
                                                to='api.CheckOutProcess', verbose_name='Check-Out-Vorgang')),
                ('checked_in_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Check-In durchgeführt von')),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
            },
        ),
    ]
