# Generated by Django 2.2.5 on 2019-09-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0015_auto_20190918_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutprocess',
            name='is_check_out_in_process',
            field=models.BooleanField(default=True, verbose_name='Check-Out im Prozess?'),
        ),
    ]
