name: Docker Image CI

on:
  push:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag tinventory:$(date +%s)

